# Nama Workflow yang akan muncul di tab "Actions" GitHub
name: Generate Snake Animation

on:
  # Dijadwalkan untuk berjalan setiap 12 jam (cron schedule)
  schedule:
    - cron: "0 */12 * * *" 
  # Mengizinkan menjalankan workflow secara manual dari GitHub UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # === SOLUSI WAJIB: MENAMBAHKAN IZIN MENULIS (WRITE) ===
    permissions:
      contents: write 
    # =======================================================
      
    steps:
      # Langkah 1: Checkout kode repositori Anda
      - uses: actions/checkout@v4
      
      # Langkah 2: Menjalankan GitHub Snake Action (Membuat Gambar Ular)
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: codemaster-d
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.svg

    # Langkah 3: Mengirim file gambar yang dihasilkan ke branch 'output'
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output # Branch tempat gambar disimpan
          build_dir: dist # Folder tempat gambar dihasilkan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
